// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: bankcard.proto

package bankcard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankcardService_ReqestingBankcard_FullMethodName = "/BankcardService/ReqestingBankcard"
)

// BankcardServiceClient is the client API for BankcardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankcardServiceClient interface {
	ReqestingBankcard(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
}

type bankcardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankcardServiceClient(cc grpc.ClientConnInterface) BankcardServiceClient {
	return &bankcardServiceClient{cc}
}

func (c *bankcardServiceClient) ReqestingBankcard(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, BankcardService_ReqestingBankcard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankcardServiceServer is the server API for BankcardService service.
// All implementations must embed UnimplementedBankcardServiceServer
// for forward compatibility.
type BankcardServiceServer interface {
	ReqestingBankcard(context.Context, *ClientRequest) (*ClientResponse, error)
	mustEmbedUnimplementedBankcardServiceServer()
}

// UnimplementedBankcardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankcardServiceServer struct{}

func (UnimplementedBankcardServiceServer) ReqestingBankcard(context.Context, *ClientRequest) (*ClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqestingBankcard not implemented")
}
func (UnimplementedBankcardServiceServer) mustEmbedUnimplementedBankcardServiceServer() {}
func (UnimplementedBankcardServiceServer) testEmbeddedByValue()                         {}

// UnsafeBankcardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankcardServiceServer will
// result in compilation errors.
type UnsafeBankcardServiceServer interface {
	mustEmbedUnimplementedBankcardServiceServer()
}

func RegisterBankcardServiceServer(s grpc.ServiceRegistrar, srv BankcardServiceServer) {
	// If the following call pancis, it indicates UnimplementedBankcardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankcardService_ServiceDesc, srv)
}

func _BankcardService_ReqestingBankcard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankcardServiceServer).ReqestingBankcard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankcardService_ReqestingBankcard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankcardServiceServer).ReqestingBankcard(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankcardService_ServiceDesc is the grpc.ServiceDesc for BankcardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankcardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BankcardService",
	HandlerType: (*BankcardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqestingBankcard",
			Handler:    _BankcardService_ReqestingBankcard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bankcard.proto",
}
